# /data/ folder required 
# manages local docker  
version: "3.5"
services:
  portainer:
    image: portainer/portainer #https://hub.docker.com/r/portainer/portainer
    container_name: portainer 
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer:/data
    ports:
     - "9000:9000"
